### ISSUE TITLE
template for explorer node

### ISSUE THREAD

**Issue by zaibon** [threefoldtoken/0-templates#2]

**Comment by LeeSmet** [comment]
## Setup

The explorer consists of both a daemon with the explorer module, and a caddy. At this point, there is no repo for the threefold explorer yet, so we are using the rivine one. In the future, we have plans to add the threefold explorer in its own repo, and provide an flist based on the daemon+client, and caddy + the required caddyfile

To run the daemon:
```
tfchaind -M gcte
```

It is important to note that the caddy acts as a proxy to this daemons' http api, and so the api address here should not be changed (unless the caddyfile is also updated)

If required, the rpc port can be changed. This daemon does not have a wallet to initialize. Like the other one, its peer discovery should be automatic. Also like the other one, you might want to specify where its data is stored

**Comment by khaledkbadr** [comment]
The explorer's flist is not ready at the moment, so I'm gonna freeze then issue until it's it's prepared.
@LeeSmet please, ping me when it's ready to continue

**Comment by zaibon** [comment]
In order to avoid code duplication, we can re-use the flist used for the block_creator template.
But we would just start the daemon with the proper module for an explorer node (`gcte`)
Then an flist with caddy and some static html file will be mounted into the container.
So the container can start caddy and reverse proxy to the daemon
