### ISSUE TITLE
Save letsencrypt certs in persistent storage

### ISSUE THREAD

**Issue by LeeSmet** [threefoldtoken/0-templates#27]
Right now it seems that the explorer generates a new set of certs every time it is restarted, while it would be preferable if they are stored so they can be reused

**Comment by LeeSmet** [comment]
@FastGeert  Seems like the storage is mounted in the wrong directory. As it turns out, the right directory is `/.caddy`, instead of the currently used `/root/.caddy`

**Comment by zaibon** [comment]
@LeeSmet this is due to the fact that zero-os container set HOME to `/` cause that's the only path that we are sure will always exists. 
So or we change the location of the mounted directory, or we set the HOME to `/root`

**Comment by LeeSmet** [comment]
Either works for me. Though i suppose changing the mounted dir is best so the home directory stays consistent with other containers

**Comment by LeeSmet** [comment]
Certs seem to be saved correctly now
