### ISSUE TITLE
Auto discover local peers through nmap

### ISSUE THREAD

**Issue by FastGeert** [threefoldtoken/0-templates#31]
To be able to run our chain on multiple nodes in a local network, we need to manually add them as peers. To make the system work, we can only add a peer once every 5 minutes.

Algorithme run every 5 minutes:
- scan local network via nmap on port 23112
- shuffle the list of peers found listening on port 23112
- find the first peer in the list to which the local tfchaind is not connected yet, and add it manually

This issue depends on: 
- https://github.com/zero-os/flists/issues/1
- https://github.com/Jumpscale/lib9/issues/264

**Comment by katia-e** [comment]
fixed in #34
