### ISSUE TITLE
Can't create block creator from existing seed

### ISSUE THREAD

**Issue by LeeSmet** [threefoldtoken/0-templates#38]
When trying to pass an existing seed when the service is created, the seed is ignored and the block creator creates a wallet with a new random seed

**Comment by zaibon** [comment]
Looking at the code now. Starting from an existing seed has never been a supported feature of this template.

**Comment by LeeSmet** [comment]
In that case, can this feature be added? since right now it seems there is no way to recover a seed, only generate new ones
